# Generated by Django 4.2.7 on 2024-10-02 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notebook',
            new_name='Notepad',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='notebook',
            new_name='notepad',
        ),
    ]
