# Generated by Django 4.2.7 on 2024-10-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_notebook_notepad_rename_notebook_note_notepad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='notepad',
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Notepad',
        ),
    ]
